### ISSUE TITLE
Need help in how to build on Windows

### ISSUE THREAD

**Issue by TianXieUnity** [lettier/3d-game-shaders-for-beginners#18]
Hi, it seems that the guide about how to build on windows is incomplete, can you help fix it ?
Really appreciate your work, huge thank you
![image](https://user-images.githubusercontent.com/71059775/99934297-94396380-2d98-11eb-9b30-f484ad350308.png)

**Comment by lettier** [comment]
Hello,

First, you'll need to [install Panda3D](https://docs.panda3d.org/1.10/cpp/introduction/installation-windows) for Windows.
Once installed, you can then [compile 3D Game Shaders For Beginners](https://docs.panda3d.org/1.10/cpp/introduction/running-your-program#compiling-your-program-with-visual-studio).

:+1:

**Comment by TianXieUnity** [comment]
Thank you , I succeed~
I find that I should add every lib you compile with mac/linux to visual studio's setting , and pay attention to the path issue.

**Comment by gonnavis** [comment]
@TianXieUnity Great! I'm not familiar with compile and failed to build, could you share the result .exe file?
My email is gonnavis@163.com, or online download link is best, thanks a lot!
