### ISSUE TITLE
can't find p3pystub

### ISSUE THREAD

**Issue by dingowizard** [lettier/3d-game-shaders-for-beginners#24]
Trying to build demo, get this error from linker:

    /usr/bin/ld: cannot find -lp3pystub
    collect2: error: ld returned 1 exit status

I have version 1.11.0 of panda3d installed on arch with samples working. I can't find p3pystub library anywhere.

thanks for any help.

**Comment by rdb** [comment]
libp3pystub was removed from Panda3D because it is no longer necessary.  You can omit it from the linker flags.

**Comment by dingowizard** [comment]
Thanks. That did it.
