### ISSUE TITLE
Get Linkers for panda

### ISSUE THREAD

**Issue by jamesthesnake** [lettier/3d-game-shaders-for-beginners#25]
When I run 
"""
          g++   3d-game-shaders-for-beginners.o   -o 3d-game-shaders-for-beginners   -L/usr/lib/panda3d   -lp3framework   -lpanda   
          -lpandafx   -lpandaexpress   -lpandaphysics   -lp3dtoolconfig   -lp3dtool   -lp3pystub   -lp3direct   -lpthread
"""

I get 

/usr/bin/ld: cannot find -lp3framework
/usr/bin/ld: cannot find -lpanda
/usr/bin/ld: cannot find -lpandafx
/usr/bin/ld: cannot find -lpandaexpress
/usr/bin/ld: cannot find -lpandaphysics
/usr/bin/ld: cannot find -lp3dtoolconfig
/usr/bin/ld: cannot find -lp3dtool
/usr/bin/ld: cannot find -lp3pystub
/usr/bin/ld: cannot find -lp3direct
collect2: error: ld returned 1 exit status

I have downloaded panda3d

**Comment by rdb** [comment]
You need to change the -L directory to the directory containing libpanda.so and friends.  This may be different from `/usr/lib/panda3d` on your system.  On some systems it is something like `/usr/lib/x86_64-linux-gnu/panda3d`.

**Comment by jamesthesnake** [comment]
New issue but I'll open a new one to reflect that.

**Comment by dmitrykolesnikovich** [comment]
> You need to change the -L directory to the directory containing libpanda.so and friends. This may be different from `/usr/lib/panda3d` on your system. On some systems it is something like `/usr/lib/x86_64-linux-gnu/panda3d`.

This fixed my issue. Thanks for the useful answer.

**Comment by dmitrykolesnikovich** [comment]
I run Ubuntu on Virual Box and get this error after successfull build and run an output executable 

![image](https://user-images.githubusercontent.com/6131040/229903441-3388a79d-0731-4171-a5df-3b50f31cc255.png)
