### ISSUE TITLE
Running Demo in Windows 

### ISSUE THREAD

**Issue by Duotun** [lettier/3d-game-shaders-for-beginners#5]
Dear David Lettier,
               I am trying to run your demo on the windows platform but it seems to be not good as that shown in your readme.md. (I have added my running result as follows)
               Can you please explain more specific methods to run your code in windows platform? I only delete the **<unistd.h>** to run the code successfully 
               Thank you very much for your precious time and efforts
Best,

              
![image](https://user-images.githubusercontent.com/29925293/58005186-a8533380-7b17-11e9-91f3-ac4a406d2196.png)

**Comment by lettier** [comment]
Hello,

Looks correct from what I can see.

You can disable certain effects by using the keyboard controls.

https://github.com/lettier/3d-game-shaders-for-beginners#toggles

Try holding down <kbd>shift</kbd> and pressing <kbd>h</kbd>, <kbd>j</kbd>, and <kbd>k</kbd>.

:+1:

**Comment by Duotun** [comment]
Cool! it turns out to be fantastic now! Thanks a lot!
![image](https://user-images.githubusercontent.com/29925293/58063905-b013e600-7bb2-11e9-963d-d6780bedf4a5.png)
