### ISSUE TITLE
shader compile error on macOS mojave 10.14.5

### ISSUE THREAD

**Issue by ourui** [lettier/3d-game-shaders-for-beginners#9]
`Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/position.frag:
ERROR: shaders/fragment/position.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/normal.frag:
ERROR: shaders/fragment/normal.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/material-diffuse.frag:
ERROR: shaders/fragment/material-diffuse.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/material-specular.frag:
ERROR: shaders/fragment/material-specular.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/foam-mask.frag:
ERROR: shaders/fragment/foam-mask.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/ssao.frag:
ERROR: shaders/fragment/ssao.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/blur.frag:
ERROR: shaders/fragment/blur.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/ssr.frag:
ERROR: shaders/fragment/ssr.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/base.vert:
ERROR: shaders/vertex/base.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/base.frag:
ERROR: shaders/fragment/base.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/fog.frag:
ERROR: shaders/fragment/fog.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/refraction.frag:
ERROR: shaders/fragment/refraction.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/outline.frag:
ERROR: shaders/fragment/outline.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/foam.frag:
ERROR: shaders/fragment/foam.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/reflection.frag:
ERROR: shaders/fragment/reflection.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/base-combine.frag:
ERROR: shaders/fragment/base-combine.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/sharpen.frag:
ERROR: shaders/fragment/sharpen.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/posterize.frag:
ERROR: shaders/fragment/posterize.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/bloom.frag:
ERROR: shaders/fragment/bloom.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/scene-combine.frag:
ERROR: shaders/fragment/scene-combine.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/depth-of-field.frag:
ERROR: shaders/fragment/depth-of-field.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/pixelize.frag:
ERROR: shaders/fragment/pixelize.frag:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader shaders/vertex/basic.vert:
ERROR: shaders/vertex/basic.vert:6: '' :  version '140' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader shaders/fragment/film-grain.frag:
ERROR: shaders/fragment/film-grain.frag:6: '' :  version '140' is not supported`

**Comment by rdb** [comment]
On macOS, you probably want to use GLSL version 150, since I've not found 140 to work.  You also then need to put `gl-version 3 2` in your Panda3D Config.prc to request a forward compatible profile.

**Comment by lettier** [comment]
Hello @ourui

I have made the suggested changes given by @rdb. Be sure to clone a fresh copy of the repository. 

Thank you @rdb.

:+1:

**Comment by ourui** [comment]
@rdb @lettier  Thanks a lot !  it works now!
